### ISSUE TITLE
hello.py doesn't run: AttributeError: module 'launchpad_py' has no attribute 'LaunchpadProMk3'

### ISSUE THREAD

**Issue by kaiyoma** [FMMT666/launchpad.py#61]
`information.py` seems to run just fine, but `hello.py` doesn't:

```
C:\Work\launchpad.py\examples>python hello.py
pygame 2.0.1 (SDL 2.0.14, Python 3.9.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
<module 'launchpad_py' from 'C:\\Python\\lib\\site-packages\\launchpad_py\\__init__.py'>
Traceback (most recent call last):
  File "C:\Work\launchpad.py\examples\hello.py", line 167, in <module>
    main()
  File "C:\Work\launchpad.py\examples\hello.py", line 38, in main
    elif launchpad.LaunchpadProMk3().Check( 0 ):
AttributeError: module 'launchpad_py' has no attribute 'LaunchpadProMk3'
```

**Comment by FMMT666** [comment]
Could it be that you have an older version installed in
the site-packages folder?

To quickly test this, you can also move the files "launchpad.py" and "charset.py"
in the same directory of the "hello.py" file.
Now, executing it from this folder will use the file "launchpad.py" file there rather than
that from the installation.
